export enum ERROR_MESSAGES {
  INCORRECT_DATA = "INCORRECT_DATA",
  DUPLICATE = "DUPLICATE",
  SERVER_ERROR = "SERVER_ERROR",
  NO_SECRET_KEY_DEFINED = "NO_SECRET_KEY_DEFINED",
}

export enum RESPONSE_MESSAGES {
  SUCCESS = "SUCCESS",
  FAILED = "FAILED",
}
